---
# tasks file for cloud-config

- name: Copy cloud config files to remote host
  copy:
    src: "{{ item.name }}"
    dest: "{{ SASHOME }}/{{ item.path }}/{{ item.name }}"
    owner: "{{ INSTALL_USER }}"
    group: "{{ INSTALL_GROUP }}"
    mode: "{{ item.mode }}"
  with_items:
  - { name: docker-functions, path: "lib/envesntl", mode: "0755" }
  - { name: docker-ops-agent, path: "lib/envesntl", mode: "0755" }
  - { name: consul-utils.sh, path: "bin", mode: "0755" }
  - { name: kill_consul_helper.sh, path: "bin", mode: "0755" }
  - { name: localconsul_generate_vault_cert.sh, path: "bin", mode: "0755" }
  - { name: sas-consul, path: "bin", mode: "0755" }
  - { name: setup_rds_postgres.sh, path: "bin", mode: "0755" }

- name: Copy sas-viya-all-services to remote host
  copy:
    src: "{{ item.name }}"
    dest: "/etc/init.d/{{ item.name }}"
    owner: "{{ INSTALL_USER }}"
    group: "{{ INSTALL_GROUP }}"
    mode: "{{ item.mode }}"
  with_items:
  - { name: sas-viya-all-services, mode: "0755" }

- name: modify sas-init-functions
  lineinfile:
    path: "{{ SASHOME }}/lib/envesntl/sas-init-functions"
    regexp: '\$RU \$uid -c "\$\*"'
    line: '  $*'

- name: list all sas init files
  find:
    paths: /etc/init.d
    patterns: "sas-*"
  register: init_files

- name: update all init files
  lineinfile:
    path: "{{ item.path }}"
    regexp: '^SASLOCKROOT="/var/lock/subsys"'
    line: 'SASLOCKROOT="/opt/sas/{{ DEPLOYMENT_ID }}/config/var/lock"'
  with_items: "{{ init_files.files }}"

