apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sas-viya-programming-single-ingress
  namespace: @REPLACE_ME_WITH_YOUR_K8S_NAMESPACE@
spec:
  rules:
  - host: sas-viya.@REPLACE_ME_WITH_YOUR_K8S_NAMESPACE@.@REPLACE_ME_WITH_YOUR_DOMAIN@
    http:
      paths:
      - backend:
          serviceName: sas-viya-single-programming-only
          servicePort: 80
#  tls:
#  - hosts:
#    - sas-viya.@REPLACE_ME_WITH_YOUR_K8S_NAMESPACE@.@REPLACE_ME_WITH_YOUR_DOMAIN@
#    secretName: @REPLACE_ME_WITH_TLS_SECRET@
